"""add a business interests table

Revision ID: 2814499ef0d3
Revises: 6cd63cebf6ff
Create Date: 2025-08-26 13:04:20.156189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2814499ef0d3'
down_revision = '6cd63cebf6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_interests_business_id_businesses')),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('fk_business_interests_interest_id_interests')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_interests')
    # ### end Alembic commands ###
