"""initial migration

Revision ID: 32a3d6530f42
Revises: 
Create Date: 2025-08-25 15:18:09.252136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a3d6530f42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('capital', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('ac_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('population', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('prefecture_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name=op.f('fk_cities_prefecture_id_prefectures')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('individuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_individuals_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('district_block', sa.String(), nullable=False),
    sa.Column('building_name', sa.String(), nullable=True),
    sa.Column('floor_room', sa.String(), nullable=True),
    sa.Column('allow_email', sa.Boolean(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_businesses_city_id_cities')),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_businesses_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_sites_city_id_cities')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], name=op.f('fk_wishlists_individual_id_individuals')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_business_wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefecture_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('sites_id', sa.Integer(), nullable=True),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_location_business_wishlists_business_id_businesses')),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_location_business_wishlists_city_id_cities')),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name=op.f('fk_location_business_wishlists_prefecture_id_prefectures')),
    sa.ForeignKeyConstraint(['sites_id'], ['sites.id'], name=op.f('fk_location_business_wishlists_sites_id_sites')),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], name=op.f('fk_location_business_wishlists_wishlist_id_wishlists')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_business_wishlists')
    op.drop_table('wishlists')
    op.drop_table('sites')
    op.drop_table('businesses')
    op.drop_table('individuals')
    op.drop_table('cities')
    op.drop_table('users')
    op.drop_table('prefectures')
    # ### end Alembic commands ###
