"""create interests table

Revision ID: 396d5cf0ac26
Revises: 32a3d6530f42
Create Date: 2025-08-26 11:21:04.368605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396d5cf0ac26'
down_revision = '32a3d6530f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('interest')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interests')
    # ### end Alembic commands ###
