"""add the business industry table

Revision ID: 3c7ecaad6459
Revises: 7f75e80b09e4
Create Date: 2025-08-26 14:08:32.318078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7ecaad6459'
down_revision = '7f75e80b09e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_industries_business_id_businesses')),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_business_industries_industry_id_industries')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_industries')
    # ### end Alembic commands ###
