"""add a wishlist table

Revision ID: 4b250b0234ce
Revises: 8b01f5880cb2
Create Date: 2025-08-25 11:00:16.595454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b250b0234ce'
down_revision = '8b01f5880cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_individual wishlists_business_id_businesses')),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], name=op.f('fk_individual wishlists_individual_id_individuals')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individual wishlists')
    # ### end Alembic commands ###
