"""initial migration

Revision ID: 686466cc5262
Revises: 
Create Date: 2025-08-24 14:41:28.483160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686466cc5262'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('capital', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefectures')
    # ### end Alembic commands ###
