"""create individual interest table

Revision ID: 6cd63cebf6ff
Revises: 396d5cf0ac26
Create Date: 2025-08-26 12:16:29.136287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd63cebf6ff'
down_revision = '396d5cf0ac26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=True),
    sa.Column('interests_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], name=op.f('fk_individual_interests_individual_id_individuals')),
    sa.ForeignKeyConstraint(['interests_id'], ['interests.id'], name=op.f('fk_individual_interests_interests_id_interests')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individual_interests')
    # ### end Alembic commands ###
