"""update location_business_wishlist table

Revision ID: afa7e35fdede
Revises: 3c7ecaad6459
Create Date: 2025-08-26 15:31:01.836421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa7e35fdede'
down_revision = '3c7ecaad6459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_business_wishlists', schema=None) as batch_op:
        batch_op.drop_constraint('fk_location_business_wishlists_city_id_cities', type_='foreignkey')
        batch_op.drop_constraint('fk_location_business_wishlists_prefecture_id_prefectures', type_='foreignkey')
        batch_op.drop_column('prefecture_id')
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_business_wishlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('prefecture_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_location_business_wishlists_prefecture_id_prefectures', 'prefectures', ['prefecture_id'], ['id'])
        batch_op.create_foreign_key('fk_location_business_wishlists_city_id_cities', 'cities', ['city_id'], ['id'])

    # ### end Alembic commands ###
