"""update wishlist table to include sites id

Revision ID: c307192ed233
Revises: 021e4ebe2c7d
Create Date: 2025-08-25 13:04:49.314627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c307192ed233'
down_revision = '021e4ebe2c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual_wishlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sites_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_individual_wishlists_sites_id_sites'), 'sites', ['sites_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual_wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_individual_wishlists_sites_id_sites'), type_='foreignkey')
        batch_op.drop_column('sites_id')

    # ### end Alembic commands ###
