"""update wishlist table name

Revision ID: d39b19c98fbf
Revises: 4b250b0234ce
Create Date: 2025-08-25 11:05:49.423044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39b19c98fbf'
down_revision = '4b250b0234ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_individual_wishlists_business_id_businesses')),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], name=op.f('fk_individual_wishlists_individual_id_individuals')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('individual wishlists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual wishlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('individual_id', sa.INTEGER(), nullable=True),
    sa.Column('business_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('individual_wishlists')
    # ### end Alembic commands ###
